// Generated by CoffeeScript 1.9.3
(function() {
  var _, all;

  _ = require('lodash');

  all = function(args) {
    var allArgs;
    allArgs = _.pick(args, ['sortBy', 'sortDirection', 'limit', 'offset']);
    return this.where(allArgs);
  };

  module.exports = all;

}).call(this);
