// Generated by CoffeeScript 1.9.3
(function() {
  var _, all, redisWhere;

  _ = require('lodash');

  redisWhere = require('./where');

  all = function(args) {
    var allArgs;
    allArgs = _.isEmpty(args) ? {} : _.pick(args, ['sortBy', 'sortDirection', 'limit', 'offset']);
    return redisWhere.apply(this, [allArgs]);
  };

  module.exports = all;

}).call(this);
