// Generated by CoffeeScript 1.9.3
(function() {
  var Promise, create, sendAttributesForSaving;

  Promise = require('promise');

  sendAttributesForSaving = require('./_redisObjectSave');

  create = function(props, skipValidation) {
    return new Promise((function(_this) {
      return function(resolve, reject) {
        return sendAttributesForSaving.apply(_this, [props, skipValidation]).then(function(writtenObject) {
          if (writtenObject) {
            return resolve(_this.find(writtenObject.id));
          }
        }, function(error) {
          if (error) {
            return reject(error);
          }
        });
      };
    })(this));
  };

  module.exports = create;

}).call(this);
