// Generated by CoffeeScript 1.9.3
(function() {
  var Promise, create, redisFind, sendAttributesForSaving;

  Promise = require('promise');

  sendAttributesForSaving = require('./_redisObjectSave');

  redisFind = require('./find');

  create = function(props, skipValidation) {
    return sendAttributesForSaving.apply(this, [props, skipValidation]).then(function(writtenObject) {
      if (!writtenObject) {
        throw new Error('Write error');
      }
      return redisFind(writtenObject.id);
    }, function(error) {
      return error;
    });
  };

  module.exports = create;

}).call(this);
