// Generated by CoffeeScript 1.9.3
(function() {
  var Promise, _, destroy, redisCreate, redisUpdate;

  Promise = require('promise');

  redisCreate = require('./create');

  redisUpdate = require('./update');

  _ = require('lodash');

  destroy = function() {
    var attr, i, len, ref, removeFields;
    if (!this.id) {
      return new Error('Can\'t find object\'s id');
    }
    removeFields = {};
    ref = Object.keys(this.constructor.classAttributes);
    for (i = 0, len = ref.length; i < len; i++) {
      attr = ref[i];
      removeFields['remove_' + attr] = this[attr] || "";
    }
    return redisUpdate.apply(this.constructor, [this.id, removeFields]).then((function(_this) {
      return function(newProps) {
        return new Promise(function(resolve, reject) {
          return _this.constructor.redis.del(_this.constructor.className + ':' + _this.id, function(err, response) {
            if (err) {
              return reject(err);
            }
            return resolve(true);
          });
        });
      };
    })(this));
  };

  module.exports = destroy;

}).call(this);
