// Generated by CoffeeScript 1.9.3
(function() {
  var Promise, destroy, redisUpdate;

  Promise = require('promise');

  redisUpdate = require('./update');

  destroy = function(id) {
    var attr, i, len, ref, removeAttributes, removeFields;
    if (!id) {
      return new Error('Can\'t find object\'s id');
    }
    removeFields = {};
    ref = Object.keys(this.classAttributes);
    for (i = 0, len = ref.length; i < len; i++) {
      attr = ref[i];
      removeFields['remove_' + attr] = this[attr] || "";
    }
    removeAttributes = redisUpdate.apply(this, [id, removeFields, true]).then((function(_this) {
      return function(newProps) {
        return new Promise(function(resolve, reject) {
          return _this.redis.zrem(_this.className + '>id', id, function(err, response) {
            return resolve();
          });
        });
      };
    })(this));
    return removeAttributes.then((function(_this) {
      return function() {
        return new Promise(function(resolve, reject) {
          return _this.redis.del(_this.className + ':' + id, function(err, response) {
            if (err) {
              return reject(err);
            }
            return resolve(true);
          });
        });
      };
    })(this));
  };

  module.exports = destroy;

}).call(this);
