// Generated by CoffeeScript 1.9.3
(function() {
  var _, redisCreate, redisUpdate, save;

  redisCreate = require('./create');

  redisUpdate = require('./update');

  _ = require('lodash');

  save = function() {
    var attr, i, len, ref, updateFields;
    if (this.id) {
      updateFields = {};
      ref = Object.keys(this.constructor.classAttributes);
      for (i = 0, len = ref.length; i < len; i++) {
        attr = ref[i];
        if (this[attr]) {
          updateFields[attr] = this[attr];
        }
      }
      return redisUpdate.apply(this.constructor, [this.id, updateFields]).then((function(_this) {
        return function(newProps) {
          return _.assign(_this, newProps);
        };
      })(this));
    } else {
      return redisCreate.apply(this.constructor, [this]).then((function(_this) {
        return function(newProps) {
          return _.assign(_this, newProps);
        };
      })(this));
    }
  };

  module.exports = save;

}).call(this);
