// Generated by CoffeeScript 1.9.3
(function() {
  var all, create, find, findBy, oomphRedisAdaptor, redis, save, update, where;

  redis = require('redis');

  all = require('./adaptorMethods/all');

  find = require('./adaptorMethods/find');

  findBy = require('./adaptorMethods/findBy');

  where = require('./adaptorMethods/where');

  create = require('./adaptorMethods/create');

  update = require('./adaptorMethods/update');

  save = require('./adaptorMethods/save');

  oomphRedisAdaptor = {
    connectAdaptor: function(_class) {
      var host, options, port;
      port = global.oomphRedisPort || 6379;
      host = global.oomphRedisHost || '127.0.0.1';
      options = global.oomphRedisOptions || {};
      _class.redis = redis.createClient(port, host, options);
      _class.create = create;
      _class.update = update;
      _class.find = find;
      _class.findBy = findBy;
      _class.where = where;
      _class.all = all;
      _class.prototype.save = save;
      return _class;
    }
  };

  module.exports = oomphRedisAdaptor;

}).call(this);
